config/routes.rb
Rails.application.routes.draw do
  post 'blog_posts/generate_epub'

  root 'blogs#index'
  get "blogs/posts"
  get 'blogs/downloads'
  get "blogs/downloaded"
  post "blogs/scrap"

end

app/models/blog.rb
class Blog
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :processing, type: Mongoid::Boolean, default: false
  field :downloaded, type: Mongoid::Boolean, default: false
  field :posts_count, type: Integer
  field :error_found, type: Mongoid::Boolean, default: false
  field :publisher
  field :license
  field :book_name
  field :language
  field :category
  index({ name: 1 }, { name: "name_index" })
  
  scope :downloaded, ->{ where(:downloaded => true ) }

  has_many :blog_posts
end

app/models/blog_post.rb
class BlogPost
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :content, type: String
  field :categories, type: Array
  field :blog_url, type: String
  field :author
  index({ blog_url: 1 }, { name: "blog_url_index" })

  belongs_to :blog, index: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_list_controller.rb
class BlogsController < ApplicationController

  def search
  end

  def posts
    if params[:url]
      blog_hostname = BlogService.new(params[:url]).detect_blog_type
      blog = Blog.where(name: blog_hostname).first
      if blog && blog.downloaded
        @posts = blog.blog_posts if blog
      else
        BlogService.new(params[:url]).delay.title_list
      end
    end
  end


end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:generate_epub]
  def generate_epub
    ids = params[:ids].split(",")
    if(ids)
      posts = BlogPost.where(:id.in => ids)
      blog = posts.first.blog
      domain = blog.name
      EbookBuilder.new(posts).build
      send_file "#{Rails.public_path}/ebooks/#{domain}/site.epub", :filename => "#{blog.book_name.gsub(" ", "_")}.epub"
    else
      render :json => false
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def search
  end

  def posts
    @posts = {}
    if params[:url]
      blog_service = BlogService.new(params[:url])
      blog_hostname = blog_service.detect_blog_type
      category = blog_service.category
      if(category)
        @blog = Blog.where(name: blog_hostname, category: category).last
      else
        @blog = Blog.where(name: blog_hostname, category: nil).last
      end
      if @blog && @blog.downloaded
        @posts = @blog.blog_posts
      end
    end
  end

  def downloads
    blog_hostname = BlogService.new(params[:url]).detect_blog_type if params[:url]
    blog = blog_hostname ? Blog.where(name: blog_hostname) : Blog
    @blogs = blog.downloaded.desc(:created_at).page(params[:page]).per(10)
  end

  def scrap
    blog_hostname = BlogService.new(params[:url]).detect_blog_type
    if(blog_hostname)
      blog = Blog.create(name: blog_hostname)
      blog.update_attributes(blog_update)
      if !blog.processing and !blog.downloaded
        BlogService.new(params[:url]).delay.title_list
        blog.processing = true
        blog.save
      end
    end
    render :json => (blog_hostname ? blog.to_json : {error: true}).to_json
  end

  def downloaded
    blog_hostname = BlogService.new(params[:url]).detect_blog_type
    blog = Blog.where(name: blog_hostname).last
    render :json => {status: (blog && blog.downloaded ? true : false)}.to_json
  end

  private
  
  def blog_update
    params.require(:blog).permit(:publisher, :license, :language, :book_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_list_helper.rb
module BlogListHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_list/index.html.erb
<div class="col-sm-12 col-md-12">
  <div class="col-md-6 col-md-offset-3">
    <h3 class="welcome-note">Convert your favourite blog into epub</h3>
      <%= form_tag('/blog_list/search', {method: "POST", role: "form", id: "search_form"}) do %>
        <div class="form-group">
          <%= text_field_tag "url", nil, class: 'form-control', id: "search_field", required: 'true' %>
        </div>
        <%= submit_tag 'search', class: "btn btn-success pull-left col-md-4 col-md-offset-4", id: "search_button" %>
        <img src="/assets/loading.gif" class="spinner" id="notify"/>
      <% end %>
  </div>
  <div class="main_content"></div>
</div>

app/views/blog_list/search.html.erb
<h1>Posts</h1>
<% if(@posts.count > 0) %>
  <p>There are <%= @posts.count %> posts. You can select post and download as epub file</p>
  <table class="table table-bordered table-responsive" id="search-result">
    <thead>
      <tr><td><input type="checkbox" id="select_all" /></td><td>id</td><td>Title</td></tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td><input type="checkbox" class="link_checkbox"></td>
        <td><%= post.id.to_s %></td>
        <td><%= post.title.html_safe  %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <form method="POST" action="/blog_posts/generate_epub" id="download_epub">
    <input type="hidden" name="ids" id="post_ids" />
    <input type="submit" id="results" class="btn btn-success" value="Download as Epub" />
  </form>
<% end %>

app/views/blog_posts/generate_epub.html.erb
<h1>BlogPosts#generate_epub</h1>
<p>Find me in app/views/blog_posts/generate_epub.html.erb</p>

app/views/blogs/downloads.html.erb
<h2>Downloads</h2>
<form action="/blogs/downloads" method="GET" class="form">
  <div class="form-group">
    <input type="search" class="form-control" name="url" placeholder="Search for blog to download" />
  </div>
  <%= submit_tag 'Search', class: "btn btn-success" %>
</form>
<table class="table table-responsive table-striped download_list">
  <tr>
      <th>Url</th>
      <th>Post count</th>
      <th>Category</th>
      <th>Downloaded on</th>
      <th>Download Link</th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.name %></td>
      <td><%= blog.posts_count %></td>
      <td><%= blog.category %></td>
      <td><%= blog.created_at.strftime("%d-%m-%Y") %></td>
      <td><a href="/blogs/posts?url=<%= blog.name %>" data-no-turbolink>Download</a></td>
    </tr>
  <% end %>
</table>
<%= paginate @blogs %>

app/views/blogs/index.html.erb
<div class="col-sm-12 col-md-12">
  <div class="col-md-6 col-md-offset-3">
    <h3 class="welcome-note">Create your favourite blog into epub</h3>
    <p class="welcome-note-tag">(Currently available for wordpress and blogspot blog)</p>
      <%= form_tag('/blogs/posts', { method: "GET", role: "form", id: "search_form"}) do %>
        <div class="form-group">
          <%= label_tag "Blog url" %>
          <%= text_field_tag "url", nil, class: 'form-control', id: "search_field", required: 'true', placeholder: "Eg. sathia27.wordpress.com or tshrinivasan.blogspot.com" %>
        </div>
        <div class="form-group">
          <%= label_tag "Book name" %>
          <%= text_field_tag "blog[book_name]", nil, class: 'form-control', required: 'true', placeholder: "Ebook name. eg. Ruby on rails blog" %>
        </div>
        <div class="form-group">
          <%= label_tag "Publisher name" %>
          <%= text_field_tag "blog[publisher]", nil, class: 'form-control', required: 'true', placeholder: "Your name. eg. Sathia" %>
        </div>
        <div class="form-group">
          <%= label_tag "License" %>
          <%= text_field_tag "blog[license]", nil, class: 'form-control', required: 'true', placeholder: "License. Eg. Creative common license" %>
        </div>
        <div class="form-group">
          <%= label_tag "Language of Book" %>
          <%= text_field_tag "blog[language]", nil, class: 'form-control', required: 'true', placeholder: "Language written blog. Eg. Tamil, English" %>
        </div>
        <div class="overflow-hidden">
          <%= submit_tag 'Create', class: "btn btn-success pull-left col-md-4 col-md-offset-4", id: "search_button", :"data-loading-text" => "Please wait.." %>
          <%= image_tag "loading.gif", alt: "Loading..", width: "45", id: "loader" %>
        </div>
      <% end %>
     <p class="list_post" ><%= link_to "List of downloads", blogs_downloads_path %></p>
  </div>
</div>

app/views/blogs/posts.html.erb
<h1>Posts</h1>
<% if(@blog && !@blog.downloaded) %>
  <div class="alert alert-danger">Processing.. Please wait until whole blogs downloaded</div>
<% end %>
<div class="alert"></div>
  <% if(@posts.count > 0) %>
    <% if(@blog && @blog.downloaded) %>
      <p>Total Posts: <%= @posts.count %> posts. Select and download</p>
    <% end %>
  <form method="POST" action="/blog_posts/generate_epub" id="download_epub">
    <input type="hidden" name="ids" id="post_ids" />
    <input type="submit" id="results" class="btn btn-success" value="Download as Epub" />
  </form>
  <table class="table table-bordered table-responsive" id="search-result">
    <thead>
      <tr><td><input type="checkbox" id="select_all" /></td><td>id</td><td>Title</td></tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td><input type="checkbox" class="link_checkbox"></td>
        <td><%= post.id.to_s %></td>
        <td><%= post.title.html_safe  %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="alert alert-danger">Sorry we could not fetch your blog posts</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Epub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "//cdn.datatables.net/1.10.0/css/jquery.dataTables.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default">
      <a href="https://github.com/sathia27/blog2ebook"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" data-no-turbolink>Blog2ebook (beta)</a>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>